### ISSUE TITLE
Showing progress to user during processing

### ISSUE THREAD

**Issue by ChiragCD** [ChiragCD/LST_Plugin#4]
As the plugin takes a few seconds, informing the user of progress would be useful. Requires changes in UI (a message box or progress bar) and corresponding functionality.

**Comment by NileshKumarGupta** [comment]
Shows a message box when processing starts

**Comment by ChiragCD** [comment]
Needs a way to continuously update user on progress. Eg. a progress bar, or a dynamically updated label.

**Comment by ChiragCD** [comment]
Handled with commit 0a095f10e2702dd06313ab6e87562d9c8ffe3001
